---
name: "Run PHPCS linter"
description: "Lint code using PHPCS"

inputs:
  rules:
    description: "PHPCS args"
    required: true
    default: '.'

runs:
  using: "docker"
  image: "docker://ghcr.io/seravo/phpcs:latest"
  args:
    - ${{ inputs.args }}
